### ISSUE TITLE
各位大佬，不支持对应的市场类型，无法下单

### ISSUE THREAD

**Issue by sqr1sqr** [sqr1sqr/-#1]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Python38\lib\site-packages\easytrader\follower.py", line 353, in trade_worker
    self._execute_trade_cmd(
  File "D:\Python38\lib\site-packages\easytrader\follower.py", line 318, in _execute_trade_cmd
    response = getattr(user, trade_cmd["action"])(**args)
  File "D:\Python38\lib\site-packages\easytrader\utils\perf.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "D:\Python38\lib\site-packages\easytrader\clienttrader.py", line 223, in sell
    return self.trade(security, price, amount)
  File "D:\Python38\lib\site-packages\easytrader\clienttrader.py", line 415, in trade
    self._set_trade_params(security, price, amount)
  File "D:\Python38\lib\site-packages\easytrader\clienttrader.py", line 461, in _set_trade_params
    self._set_stock_exchange_type("上海Ａ股")
  File "D:\Python38\lib\site-packages\easytrader\clienttrader.py", line 321, in _set_stock_exchange_type
    raise TypeError("不支持对应的市场类型: {}".format(ttype))
TypeError: 不支持对应的市场类型: 上海Ａ股

**Comment by 13982350886** [comment]
sendinpu() inserted only 0 out of 2 keybard events 使用easytrader时报错，怎么解决
